### PR TITLE
Readme extended, make big uploads working, more test passed

### PR DESCRIPTION
**Pull request by Gomez**
I worked with @DeepDiver1975 on get Jenkins &  Acceptance-testing running.

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
Looks good from my point of view.
@butonic @jakobsack you guys want to have a look too? THX

**Comment by jakobsack** [comment]
Hi, this pull request can **NOT** be merged for the following reasons:
1. It changes the apache cookbook which is a simple copy of http://community.opscode.com/cookbooks/apache2/source ! Another solution is needed, the ownCloud recipe could ship its own apache config
2. It disables the apps2 repository. I think it is important to check if the apps2 repository "works" (without adding extra tests) because most people will download it right away, furthermore the provisioning API is needed which resides in apps2.

**Comment by DeepDiver1975** [comment]
@jakobsack 
1. Can you please point us to any kind of documentation on how to ship our own apache config?
2. Good catch on the provisioning API - I didn't think of that. We basically disabled the apps repo because the firstrunwizard is popping up on the first login and causes all tests to fail. Can we disable the firstrunwizard app with the provisioning api?

THX

**Comment by jakobsack** [comment]
@DeepDiver1975 
1. You can enable/disable sites using the "apache_site" command from the apache recipe. Probably it's something like 
   
   ``` ruby
   apache_site "default" do
       enable false
   end
   apache_site "owncloud" do
       enable true
   end
   ```
   
   Of course you have to create a config called "owncloud" for this, use a nomal "template"-Block for this. Instead of disabling the apache default site you could prevent the apache recipe from enabling the default site by setting node['apache']['default_site_enabled'] to false in Vagrantfile
2. Once the provisioning api has been enabled you could add the following block:
   
   ``` ruby
   # Disabling firstrunwizard
   execute "Disabling firstrunwizard" do
       command "curl -X DELETE -u admin:admin " +
               " localhost/ocs/v1.php/cloud/apps/firstrunwizard"
   end
   ```
   
   See apps/provisioning_api/appinfo/routes.php and apps/provisioning_api/libs/apps.php for more details

Note that I did not test these proposals!

**Comment by DeepDiver1975** [comment]
@jakobsack Awesome! THX

**Comment by DeepDiver1975** [comment]
@Gomez do you have time to incorporate Jakob's suggestions? THX

**Comment by Gomez** [comment]
@DeepDiver1975 I will try, but cant do anything this week :(

**Comment by DeepDiver1975** [comment]
No Prob - thx

Am Dienstag, dem 19.02.2013 um 10:35 schrieb Steffen Lindner:

**Comment by Gomez** [comment]
cherrypicked the usefull stuff

**Pull request closed without merging**
