### PR TITLE
[WIP] Added acceptance test for the user management list

### PR DESCRIPTION
**Pull request by PVince81**
My first time with ruby, cucumber, etc

For some reason the groups selector doesn't want to match (it works in the browser), need to find a solution.

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
Nice! Great move @PVince81 - thanks for stepping in!

**Comment by karlitschek** [comment]
Nice :+1:

**Comment by PVince81** [comment]
I've added user creation scenario.

I hope to be able to pre-init the tests with the test users later ("Background: Given that user user1 exists...") so we can get rid of the README instructions and only need the "admin" user at the beginning.

**Comment by PVince81** [comment]
Note to self: use simulated ajax calls to create/delete users when preparing the test cases ("Given that user user1 exists")

**Pull request closed without merging**
